# Generated by Django 6.0 on 2025-12-16 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0002_remove_formdefinition_storage_key_formsubmission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formdefinition',
            name='kind',
            field=models.CharField(choices=[('GENERIC', 'Generic'), ('HEALTHCHECK', 'Health Check'), ('COFFEE', 'Coffee Morning')], default='GENERIC', max_length=30),
        ),
        migrations.AlterField(
            model_name='formdefinition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formdefinition',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
