# Generated by Django 6.0 on 2025-12-18 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0003_formdefinition_kind_alter_formdefinition_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiabetesRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('age_score', models.IntegerField()),
                ('gender_score', models.IntegerField()),
                ('ethnicity_score', models.IntegerField()),
                ('family_history_score', models.IntegerField()),
                ('waist_score', models.IntegerField()),
                ('bmi_score', models.IntegerField()),
                ('bp_score', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('risk_level', models.CharField(max_length=30)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
