# Generated by Django 6.0 on 2025-12-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0004_diabetesriskassessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiabetesRiskAssessment',
        ),
    ]
