# Generated by Django 6.0 on 2025-12-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0005_delete_diabetesriskassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdefinition',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
