# Generated by Django 6.0 on 2025-12-18 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0006_formdefinition_is_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='choices_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='key',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
