# Generated by Django 6.0 on 2025-12-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0007_alter_formfield_choices_text_alter_formfield_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='is_displayed',
            field=models.BooleanField(default=True),
        ),
    ]
