# Generated by Django 6.0 on 2025-12-22 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0008_formfield_is_displayed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdefinition',
            name='is_system',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='is_displayed',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='forename',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='choices_text',
            field=models.TextField(blank=True, help_text='For Choice type: one option per line'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='key',
            field=models.SlugField(help_text='Unique key like: bmi, diastolic, postcode'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['surname', 'forename'], name='forms_build_surname_8e3b99_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['postcode'], name='forms_build_postcod_6d6af7_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['date_of_birth'], name='forms_build_date_of_d6c1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form', 'submitted_at'], name='forms_build_form_id_de1889_idx'),
        ),
    ]
