# Generated by Django 6.0 on 2026-01-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0009_remove_formdefinition_is_system_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='formsubmission',
            name='forms_build_surname_8e3b99_idx',
        ),
        migrations.RemoveIndex(
            model_name='formsubmission',
            name='forms_build_postcod_6d6af7_idx',
        ),
        migrations.RemoveIndex(
            model_name='formsubmission',
            name='forms_build_date_of_d6c1fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='formsubmission',
            name='forms_build_form_id_de1889_idx',
        ),
        migrations.RemoveField(
            model_name='formdefinition',
            name='kind',
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='forename',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
