# Generated by Codex on 2026-01-17

from django.db import migrations


def create_coffee_morning_form(apps, schema_editor):
    FormDefinition = apps.get_model("forms_builder", "FormDefinition")
    FormField = apps.get_model("forms_builder", "FormField")

    form = FormDefinition.objects.filter(name__iexact="Coffee Morning").first()
    if not form:
        form = FormDefinition.objects.create(
            name="Coffee Morning",
            description="Coffee Morning attendance",
        )

    fields = [
        {"key": "forename", "label": "Forename", "field_type": "text", "required": True},
        {"key": "surname", "label": "Surname", "field_type": "text", "required": True},
        {"key": "gender", "label": "Gender", "field_type": "choice", "required": False, "choices_text": "F\nM"},
        {"key": "ethnicity", "label": "Ethnicity", "field_type": "choice", "required": False, "choices_text": "WHITE\nOTHER"},
        {"key": "postcode", "label": "Postcode", "field_type": "text", "required": False},
        {"key": "gp", "label": "GP", "field_type": "text", "required": False},
        {"key": "date_of_birth", "label": "Date of birth", "field_type": "date", "required": False},
    ]

    for order, data in enumerate(fields):
        defaults = {
            "label": data["label"],
            "field_type": data["field_type"],
            "required": data["required"],
            "choices_text": data.get("choices_text", ""),
            "order": order,
        }
        obj, created = FormField.objects.get_or_create(
            form=form,
            key=data["key"],
            defaults=defaults,
        )
        if not created:
            updates = {}
            for key, value in defaults.items():
                if getattr(obj, key) != value:
                    updates[key] = value
            if updates:
                for key, value in updates.items():
                    setattr(obj, key, value)
                obj.save(update_fields=list(updates.keys()))


def remove_coffee_morning_form(apps, schema_editor):
    FormDefinition = apps.get_model("forms_builder", "FormDefinition")
    form = FormDefinition.objects.filter(name__iexact="Coffee Morning").first()
    if form:
        form.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0010_remove_formsubmission_forms_build_surname_8e3b99_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(create_coffee_morning_form, remove_coffee_morning_form),
    ]
