# Generated by Codex on 2026-01-17

from django.db import migrations, models


def set_form_order(apps, schema_editor):
    FormDefinition = apps.get_model("forms_builder", "FormDefinition")
    qs = FormDefinition.objects.all().order_by("created_at", "id")
    for idx, form in enumerate(qs):
        if form.order != idx:
            FormDefinition.objects.filter(id=form.id).update(order=idx)


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0011_create_coffee_morning_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(set_form_order, migrations.RunPython.noop),
    ]
