# Generated by Django 6.0 on 2025-12-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_diabetesriskassessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='age_score',
        ),
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='bmi_score',
        ),
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='bp_score',
        ),
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='ethnicity_score',
        ),
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='family_history_score',
        ),
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='gender_score',
        ),
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='waist_score',
        ),
    ]
