# Generated by Django 6.0 on 2025-12-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_diabetesriskassessment_age_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='age_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='bmi_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='bp_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='ethnicity_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='family_history_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='gender_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='waist_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
