# Generated by Django 6.0 on 2025-12-19 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_diabetesriskassessment_age_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diabetesriskassessment',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='age_band',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='bmi',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='diastolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='ethnicity',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='family_history',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='forename',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='gender',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='gp',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='height_cm',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='high_bp',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='json_path',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='pulse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='surname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='waist_cm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='weight_kg',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='submitted_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='diabetes_risk_assessments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
