# Generated by Django 6.0 on 2025-12-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_diabetesriskassessment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='risk_level',
        ),
    ]
