# Generated by Django 6.0 on 2025-12-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_remove_diabetesriskassessment_risk_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='age_band',
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='age',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
