# Generated by Django 6.0 on 2025-12-19 14:58

from django.db import migrations, models
from datetime import date

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_diabetesriskassessment_age_band_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='age',
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='date_of_birth',
            field=models.DateField(default=date(2000, 1, 1)
),
            preserve_default=False,
        ),
    ]
