# Generated by Django 6.0 on 2026-01-17 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_diabetesriskassessment_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthCheck',
        ),
    ]
