# Generated by Django 6.0 on 2026-01-17 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_delete_healthcheck'),
        ('forms_builder', '0010_remove_formsubmission_forms_build_surname_8e3b99_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='age_score',
        ),
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='bmi_score',
        ),
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='bp_score',
        ),
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='ethnicity_score',
        ),
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='family_history',
        ),
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='family_history_score',
        ),
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='gender_score',
        ),
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='high_bp',
        ),
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='json_path',
        ),
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='waist_score',
        ),
        migrations.AddField(
            model_name='diabetesriskassessment',
            name='submission',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='risk_record', to='forms_builder.formsubmission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='ethnicity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='forename',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='gp',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='height_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='submitted_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='waist_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddIndex(
            model_name='diabetesriskassessment',
            index=models.Index(fields=['surname', 'forename'], name='crm_diabete_surname_93ac23_idx'),
        ),
        migrations.AddIndex(
            model_name='diabetesriskassessment',
            index=models.Index(fields=['postcode'], name='crm_diabete_postcod_cde4be_idx'),
        ),
        migrations.AddIndex(
            model_name='diabetesriskassessment',
            index=models.Index(fields=['submitted_at'], name='crm_diabete_submitt_932275_idx'),
        ),
        migrations.AddIndex(
            model_name='diabetesriskassessment',
            index=models.Index(fields=['bmi'], name='crm_diabete_bmi_599660_idx'),
        ),
        migrations.AddIndex(
            model_name='diabetesriskassessment',
            index=models.Index(fields=['total_score'], name='crm_diabete_total_s_f82173_idx'),
        ),
    ]
