# Generated by Django 6.0 on 2026-01-17 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_remove_diabetesriskassessment_age_score_and_more'),
        ('forms_builder', '0010_remove_formsubmission_forms_build_surname_8e3b99_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diabetes_risk', to='forms_builder.formsubmission'),
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diabetes_risk_assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
