# Generated by Django 6.0 on 2026-01-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_diabetesriskassessment_submission_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='diabetesriskassessment',
            name='crm_diabete_surname_93ac23_idx',
        ),
        migrations.RemoveIndex(
            model_name='diabetesriskassessment',
            name='crm_diabete_postcod_cde4be_idx',
        ),
        migrations.RemoveIndex(
            model_name='diabetesriskassessment',
            name='crm_diabete_submitt_932275_idx',
        ),
        migrations.RemoveIndex(
            model_name='diabetesriskassessment',
            name='crm_diabete_bmi_599660_idx',
        ),
        migrations.RemoveIndex(
            model_name='diabetesriskassessment',
            name='crm_diabete_total_s_f82173_idx',
        ),
        migrations.AlterField(
            model_name='diabetesriskassessment',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='diabetesriskassessment',
            name='submission',
        ),
    ]
