# Generated by Codex on 2026-01-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_remove_diabetesriskassessment_crm_diabete_surname_93ac23_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoffeeMorning",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("forename", models.CharField(blank=True, default="", max_length=100)),
                ("surname", models.CharField(blank=True, default="", max_length=100)),
                ("postcode", models.CharField(blank=True, default="", max_length=20)),
                ("gp", models.CharField(blank=True, default="", max_length=150)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, default="", max_length=10)),
                ("ethnicity", models.CharField(blank=True, default="", max_length=50)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coffee_mornings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coffee Morning",
                "verbose_name_plural": "Coffee Mornings",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
